In [1]:
import numpy as np

In [7]:
powers = np.random.randn(8, 4)
f = 1.02

In [6]:
powers

array([[-0.72393147,  1.46898025,  0.85498726,  0.08916172],
       [ 0.35434179, -1.06692852,  0.42126777, -1.91386037],
       [ 1.16920339,  1.69903811, -0.80407818,  2.44333196],
       [ 0.53056351,  0.96679199,  2.37317308, -1.60081613],
       [ 0.04863863,  1.08600458,  0.29855841,  3.03392866],
       [ 0.16891252, -0.1900839 ,  0.1400505 ,  1.1463457 ],
       [-1.2084939 ,  1.31733282, -2.06762343,  0.13860729],
       [ 0.04008751, -0.17146921,  0.06849113,  0.90549393]])

In [9]:
f_x = f ** np.arange(powers.shape[0])

array([1.        , 1.02      , 1.0404    , 1.061208  , 1.08243216,
       1.1040808 , 1.12616242, 1.14868567])

In [14]:
x = np.arange(powers.shape[0])
y = np.arange(powers.shape[1])

In [19]:
np.zeros(powers.shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
)

In [29]:
0.98 ** A

array([[1.        , 0.98      , 0.9604    , 0.941192  ],
       [0.98      , 0.98      , 0.9604    , 0.941192  ],
       [0.9604    , 0.9604    , 0.9604    , 0.941192  ],
       [0.941192  , 0.941192  , 0.941192  , 0.941192  ],
       [0.92236816, 0.92236816, 0.92236816, 0.92236816],
       [0.9039208 , 0.9039208 , 0.9039208 , 0.9039208 ],
       [0.88584238, 0.88584238, 0.88584238, 0.88584238],
       [0.86812553, 0.86812553, 0.86812553, 0.86812553]])

In [30]:
A.shape

(8, 4)